### ISSUE TITLE
Broken inside docker

### ISSUE THREAD

**Issue by mrprompt** [mrprompt/deploybot-cli#4]
```
root@8800c4ad32f7:/# deploybot 
Traceback (most recent call last):
  File "/usr/local/bin/deploybot", line 9, in <module>
    load_entry_point('deploybot-cli==0.2.9', 'console_scripts', 'deploybot')()
  File "/usr/local/lib/python2.7/dist-packages/cli/__init__.py", line 200, in main
    tableprint.table(data, headers=header, width=int(column_width), style=style, out=out)
  File "/usr/local/lib/python2.7/dist-packages/tableprint/printer.py", line 113, in table
    out.write('\n'.join(tablestr) + '\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-66: ordinal not in range(128)
```

**Comment by mrprompt** [comment]
fixed by #3
