### ISSUE TITLE
environment list error

### ISSUE THREAD

**Issue by mrprompt** [mrprompt/deploybot-cli#7]
run: 

' ' ' 
deploybot environment list
' ' '

output:
' ' '
Traceback (most recent call last):
  File "/usr/local/bin/deploybot", line 9, in <module>
    load_entry_point('deploybot-cli==0.3.1', 'console_scripts', 'deploybot')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cli/environment.py", line 25, in environment_list
    data = response('environment', 'list', result)
  File "/usr/local/lib/python2.7/dist-packages/cli/__init__.py", line 106, in response
    for item in items[1][1]:
IndexError: list index out of range
' ' '

**Comment by mrprompt** [comment]
fixed on 0.3.2
